services:
  github-runner:
    image: chaddyc/gha-runner:latest
    container_name: <container-name>
    environment:
      - GITHUB_URL=https://github.com/<your-org-or-repo>
      - RUNNER_TOKEN=<your-runner-token>
      - RUNNER_NAME=<your-runner-name>
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
