name: Docker Test

on:
  pull_request:
    branches:
      - main

jobs:
  docker-test:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
      REPO: ${{ github.event.repository.name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEM
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build ubuntu 22.04
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          build-arg: UBUNTU_VERSION=22.04
          push: false
          tags: chaddyc/${{ github.event.repository.name }}:22.04

      - name: Build ubuntu 24.04
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          build-arg: UBUNTU_VERSION=24.04
          push: false
          tags: chaddyc/${{ github.event.repository.name }}:24.04

      - name: Build ubuntu latest
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          build-arg: UBUNTU_VERSION=latest
          push: false
          tags: chaddyc/${{ github.event.repository.name }}:latest

  
